version: "3.4"
services:
  db:
    image: postgres:latest
    ports:
    - "5432:5432"
    expose: ["5432"]
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    image: dpage/pgadmin4
    ports:
    - "5050:5050"
    networks:
      - default
    environment:
      - PGADMIN_DEFAULT_EMAIL=colehoul@gmail.com
      - PGADMIN_DEFAULT_USER=root
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_LISTEN_PORT=5050
    depends_on:
      - db
    volumes:
    - pgadmin:/var/lib/pgadmin
  
  backend:
    depends_on:
      - db
    ports:
    - "5001:5001"
    volumes:
    - ./app/:/app/
    command: python3 -m uvicorn main:app --reload --host=0.0.0.0 --port=5001
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=api
    build:
      context: app/
      dockerfile: Dockerfile

#  frontend:
#    build:
#      context: frontend
#      args:
#        FRONTEND_ENV: ${FRONTEND_ENV-production}

volumes:
  app-db-data:
  pgadmin:
